### ISSUE TITLE
파이썬 파일 생성 요청

### ISSUE THREAD

**Issue by MisooKim2** [SeokyeongKim/PY202309-P#1]
석영학생 안녕하세요. 퀄리티 높은 보고서와 코드는 잘 확인하였습니다.

프로젝트 진척 사항은 올려주신 쥬피터 노트북으로 평가하였습니다.

다만 아쉽게도 기말 프로젝트는 파이썬 파일로 제출하는 것으로 공지를 드렸었습니다. 

평가의 일관성을 위해서 미리 공지해드린 사항이니, 쥬피터 노트북을 python 파일로 변경하여 최종 프로젝트를 마무리 해주시길 바랍니다.

시각화한 후 정보를 사용자에게 제공하는 부분에서 어려움이 생긴다면, 그냥 해당 이미지를 저장하거나 보고서를 작성하는 수준으로 기능을 변경하셔도 될 것 같습니다.

**Comment by SeokyeongKim** [comment]
안녕하세요 교수님.
IoT인공지능융합전공 김석영 학생입니다. 

말씀해주신 부분 수정하여 main.py로 분리해주었습니다.
다만 파이썬 파일엔 시각화하는 코드는 제외하고, 메인 기능만 수행하도록 하였습니다.
한 가지 고려사항으로는 데이터 전처리로 인해 main.py의 실행시간이 약 3분 정도 걸린다는 점 참고해주시면 감사하겠습니다.
감사합니다.

![image](https://github.com/SeokyeongKim/PY202309-P/assets/91733447/ce4e6130-5552-4ffb-b94c-9f775becdb9a)
